interface PosDictionary {
    [key: string]: string
}

export enum PartsOfSpeech {
    ADD,
    AFX,
    CC,
    CD,
    DT,
    EX,
    FW,
    HYPH,
    IN,
    JJ,
    JJR,
    JJS,
    LS,
    MD,
    NFP,
    NN,
    NNP,
    NNPS,
    NNS,
    PDT,
    POS,
    PRP,
    PRPQ,
    RB,
    RBR,
    RBS,
    RP,
    SYM,
    TO,
    UH,
    VB,
    VBD,
    VBG,
    VBN,
    VBP,
    VBZ,
    WDT,
    WP,
    WPQ,
    WR,
    XX,

    // Constants that the model doesn't use but that I am
    TENSE,
    PERFECTIVE
}

export enum Case {
    NOMINATIVE,
    ACCUSATIVE
}

export const posDictionary: PosDictionary = {
    ADD: "Email",
    AFX: "Affix",
    CC: "Coordinating conjunction",
    CD: "Cardinal number",
    DT: "Determiner",
    EX: "Existential there",
    FW: "Foreign word",
    HYPH: "Hyphen",
    IN: "Preposition or subordinating conjunction",
    JJ: "Adjective",
    JJR: "	Adjective, comparative",
    JJS: "Adjective, superlative",
    LS: "List item marker",
    MD: " Modal",
    NFP: "Superfluous punctuation",
    NN: " Noun, singular or mass",
    NNP: " Proper noun, singular",
    NNPS: "Proper noun, plural",
    NNS: "Noun, plural",
    PDT: "Predeterminer",
    POS: "Possessive ending",
    PRP: "Personal pronoun",
    PRP$: "Possessive pronoun",
    RB: "Adverb",
    RBR: "Adverb, comparative",
    RBS: "Adverb, superlative",
    RP: "Particle",
    SYM: "Symbol",
    TO: "to",
    UH: "Interjection",
    VB: "Verb, base form",
    VBD: "Verb, past tense",
    VBG: "Verb, gerund or present participle",
    VBN: "Verb, past participle",
    VBP: "Verb, non-3rd person singular present",
    VBZ: "Verb, 3rd person singular present",
    WDT: "Wh - determiner",
    WP: "Wh - pronoun",
    WP$: "Possessive wh - pronoun",
    WRB: "Wh - adverb",
    XX: "Unknown",
}