interface PosDictionary {
    [key: string]: string
}

export enum PartsOfSpeech {
    ADD,
    AFX,
    CC,
    CD,
    DT,
    EX,
    FW,
    HYPH,
    IN,
    JJ,
    JJR,
    JJS,
    LS,
    MD,
    NFP,
    NN,
    NNP,
    NNPS,
    NNS,
    PDT,
    POS,
    PRP,
    PRPQ,
    RB,
    RBR,
    RBS,
    RP,
    SYM,
    TO,
    UH,
    VB,
    VBD,
    VBG,
    VBN,
    VBP,
    VBZ,
    WDT,
    WP,
    WPQ,
    WR,
    XX,
    // Constants that the model doesn't use but that I am
    VBINF,
    TENSE,
    NEGATION,
    PERFECTIVE,
    QTense,
    CAUSATIVE,
    PASSIVE,
    PsvAgr,
    InfAgr,
    AdvAgr,
    SUPERLATIVE,
    COMPARATIVE,
    IMPERSONAL,
    WHNoun,
    WHAdverb,
    PRESENT,
    PAST,
    AdjectivalNoun,
    CONJUNCTION
}

export enum Case {
    NOMINATIVE,
    ACCUSATIVE
}

export const posDictionary: PosDictionary = {
    ADD: "Email",
    AFX: "Affix",
    CC: "Coordinating conjunction",
    CD: "Cardinal number",
    DT: "Determiner",
    EX: "Existential there",
    FW: "Foreign word",
    HYPH: "Hyphen",
    IN: "Preposition or subordinating conjunction",
    JJ: "Adjective",
    JJR: "	Adjective, comparative",
    JJS: "Adjective, superlative",
    LS: "List item marker",
    MD: " Modal",
    NFP: "Superfluous punctuation",
    NN: " Noun, singular or mass",
    NNP: " Proper noun, singular",
    NNPS: "Proper noun, plural",
    NNS: "Noun, plural",
    PDT: "Predeterminer",
    POS: "Possessive ending",
    PRP: "Personal pronoun",
    PRP$: "Possessive pronoun",
    RB: "Adverb",
    RBR: "Adverb, comparative",
    RBS: "Adverb, superlative",
    RP: "Particle",
    SYM: "Symbol",
    TO: "to",
    UH: "Interjection",
    VB: "Verb, base form",
    VBD: "Verb, past tense",
    VBG: "Verb, gerund or present participle",
    VBN: "Verb, past participle",
    VBP: "Verb, non-3rd person singular present",
    VBZ: "Verb, 3rd person singular present",
    WDT: "Wh - determiner",
    WP: "Wh - pronoun",
    WP$: "Possessive wh - pronoun",
    WRB: "Wh - adverb",
    XX: "Unknown",
}

export const conjunctions: string[] =
    [
        "that",
        "if",
        "whether",
        "and",
        "or",
        "while",
        "because"
    ]

export const ecmVerbs: string[] =
    [
        "see",
        "saw",
        "hear",
        "smell",
        "sense",
        "taste",
        "watch",
        "observe",
        "feel",
        "felt",
        "notice",
        "believe",
        "predict",
        "suppose",
        "imagine",
        "deem",
        "find",
        "found",
        "estimate",
    ]

export const objectControlVerbs: string[] =
    [
        "ask",
        "tell",
        "told",
        "teach",
        "taught",
        "signal",
        "persuade",
        "remind",
        "warn",
        "invite",
        "convince",
        "motivate",
        "beg",
        "motion",
        "encourage",
        "pay",
        "paid"
    ]

export const raisingVerbs: string[] =
    [
        "want",
        "need",
        "expect",
        "know",
        "knew",
        "consider",
        "think",
        "thought",
        "presume",
        "judge",
        "report"
    ]

export const impersonalVerbs: string[] =
    [
        "happen",
        "seem",
        "appear",
        "turn out",
        "transpire",
        "emerge",
        "follow",
        "occur",
        "mean",
        "result"
    ]

export const ditransitiveList: string[] =
    [
        "allow",
        "ask",
        "bake",
        "bet",
        "borrow",
        "bring",
        "buy",
        "call",
        "conceive",
        "consider",
        "cost",
        "deem",
        "deny",
        "feed",
        "find",
        "forbid",
        "get",
        "give",
        "grant",
        "hand",
        "loan",
        "mail",
        "make",
        "name",
        "owe",
        "pass",
        "promise",
        "refuse",
        "render",
        "sell",
        "send",
        "teach",
        "tell",
        "wish",
        "write"
    ]